version: '3.5'

services:
    engine:
        image: node:12
        container_name: coveo_scripts
        ports:
            - ${SERVER_PORT}:${SERVER_PORT}
        entrypoint: npm start
        env_file: .env
        volumes:
            - ./:/www
        working_dir: /www