export default {
    "searchpage:update": "command.updatecoveosearchpage",
    "create:component": "command.createcomponent",
    "component:create": "command.createcomponent",
    "build": "command.build",
    "create:project": "command.createproject",
    "project:create": "command.createproject",
    "serve": "command.server",
    "create:sandbox": "command.sandbox",
    "sandbox:create": "command.sandbox",
    "create:stylesheet": "command.createstylesheet",
    "stylesheet:create": "command.createstylesheet",
    "create:readme": "command.createreadme",
    "readme:create": "command.createreadme",
}
